[package]
name = "hasher"
version = "0.1.0"
authors = ["laser <l@s3r.me>"]
edition = "2018"
license = "MIT"

[lib]
crate-type = ["staticlib"]

[dependencies]
sha2 = "0.8.0"
memmap = "0.7.0"
libc = "0.2.58"

[build-dependencies]
cbindgen = "= 0.10.0"
